### ISSUE TITLE
I  also meet the same question, have u resolved it ?

### ISSUE THREAD

**Issue by ixyzorg** [kgarchie/Ticketer#3]
I am using nuxt 3 to create a web app where users can upload files. For now, I store them in the public folder where I assumed they would get served to users

Other files like favicon get served but not the uploaded files, I get a 404 error, during yarn dev it seems to work fine but not after building with yarn build. [this is screenshot of the folder](https://i.sstatic.net/MdLut.png) the favicon.ico, can be accessed but not the newly uploaded screenshot. How can I mitigate this?

I  also meet this question, have u resolved it ?

**Comment by PrimalDjinn** [comment]
Hello, yes.

So turns out it only works in the dev server because in production, Nuxt caches the contents of the public folder, thus any new content will not be available.

If in production just use Nginx to serve the files, or create an endpoint to serve the files manually,

Also note: If you choose to write endpoints to serve the files manually, you will need to enable read and write permissions on the folder you are going to use, also, it won't work on platforms that build edge functions like Vercel.

**Comment by PrimalDjinn** [comment]
For this project, I decided to write a custom driver using https://unstorage.unjs.io/ to read, write and store my files. It's quite versatile. It's not fully working however.

**Comment by ixyzorg** [comment]
thanks, my project also use https://unstorage.unjs.io/ to storage my file in public, I will try the nginx reverse proxy pulic folder). this is my project `https://github.com/ixyzorg/nuxt-blog-ts.git`
god blesh U
thanks
